### ISSUE TITLE
Several Gotchas!

### ISSUE THREAD

**Issue by cebola2** [akilli/ck4-detail#1]
Several Gotchas while trying to install this plugin:
-- Its name is "Detail", not "Details". Add "detail" to your list of extraplugins.
-- the source unpacks on Linux with restrictive permissions on directories unlike other plugins. chmod 755 to directories solves this.
-- to get a menu entry you need to add "Detail" as a menu entry.

**Comment by akilli** [comment]
"Gotcha" 1 and 3:
The plugin name is "detail" and the folder name is "detail" too. "details" is another plugin as you might have figured out. So you just used the wrong plugin name, therefore it was not loaded.

"Gotcha" 2:
700 and 755 are both common directory permissions. Check p.e. the permissions when you download the editor with the online builder. I might change the permissions with the next release, but as you already wrote, you can always use chmod to adjust the permissions.
